#!/bin/sh
set -eu

cd "$(dirname "$0")/.."

BUNDLE_ID="${TOKENCOFFEE_BUNDLE_ID:-com.pardeike.TokenCoffee}"
CLOUDKIT_ENVIRONMENT="${TOKENCOFFEE_CLOUDKIT_ENVIRONMENT:-Development}"
PROVISIONING_ARGS=""
SIGNING_ARGS="CODE_SIGNING_ALLOWED=NO"

if [ -n "${TOKENCOFFEE_DEVELOPMENT_TEAM:-}" ]; then
  PROVISIONING_ARGS="-allowProvisioningUpdates"
  SIGNING_ARGS="CODE_SIGNING_ALLOWED=YES CODE_SIGN_STYLE=Automatic DEVELOPMENT_TEAM=$TOKENCOFFEE_DEVELOPMENT_TEAM PRODUCT_BUNDLE_IDENTIFIER=$BUNDLE_ID CLOUDKIT_CONTAINER_ENVIRONMENT=$CLOUDKIT_ENVIRONMENT"
fi

xcodegen generate
xcodebuild $PROVISIONING_ARGS -scheme TokenCoffee -configuration Debug build $SIGNING_ARGS
